# version: '3.4'

# services:
#   taskservice.api:
#     image: ${DOCKER_REGISTRY-}taskserviceapi
#     build:
#       context: .
#       dockerfile: TaskService.API/Dockerfile

version: '3.4'

services:
  task-service:
    image: ${DOCKER_REGISTRY-}taskservice
    build:
      context: .
      dockerfile: TaskService.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskdb;Username=postgres;Password=postgrespw
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
